### PR TITLE
Backend Resources Added  (Golang)

### PR DESCRIPTION
**Pull request by devjj248**

### CODE REVIEW

**Comment by devjj248** [comment]
@debrajhyper Please check this PR

**Comment by debrajhyper** [comment]
Hey, it seems to be conflicting with the main branch. would you look after this issue.
Thanks a lot for your contribution.
Looking forward for more such resources which helps others and make the community grow. ❤

**Comment by devjj248** [comment]
@debrajhyper Check now please

**Comment by debrajhyper** [comment]
Hey @devjj248 please sync with the current updates in the main branch before PR.

**Comment by devjj248** [comment]
Done with it

**Pull request merged**
