### PR TITLE
Added one resource on Backend Development and also sorted the order

### PR DESCRIPTION
**Pull request by dhruvjain896**
Added one resource on Backend Development and also sorted the order.

### CODE REVIEW

**Comment by debrajhyper** [comment]
Hey, it seems to be conflicting with the main branch. would you look after this issue.
Thanks a lot for your contribution.
Looking forward for more such resources which helps others and make the community grow. ❤

**Comment by dhruvjain896** [comment]
Resolved the conflict please accept the pull request.

**Comment by debrajhyper** [comment]
Hey @dhruvjain896 please add your unique resources according to the context of that resources

**Comment by dhruvjain896** [comment]
> Hey @dhruvjain896 please add your unique resources according to the context of that resources

Hi @debrajhyper Flask is a backend development framework in Python and I have added the resource in Backend Development. Could you please elaborate the issue with my commit so that I can resolve it.

**Comment by debrajhyper** [comment]
hey @dhruvjain896 make sure to update the branch then make the PR.

**Pull request closed without merging**
