### PR TITLE
Backend Development Resources added

### PR DESCRIPTION
**Pull request by JunaidJaved248**
Ruby on Rails Video Tutorials Added in Backend Development

### CODE REVIEW

**Comment by JunaidJaved248** [comment]
@debrajhyper Please review this PR

**Comment by JunaidJaved248** [comment]
@debrajhyper Can you please review it

**Comment by JunaidJaved248** [comment]
@debrajhyper approve this PR please

**Comment by debrajhyper** [comment]
Thanks a lot for your contributions.
Looking forward for more such resources which helps others and make the community grow. ❤

**Pull request merged**
