### PR TITLE
add reactjs resource

### PR DESCRIPTION
**Pull request by swatiaggrawal**
Added a ReactJS course

### CODE REVIEW

**Comment by swatiaggrawal** [comment]
Please review

**Comment by debrajhyper** [comment]
Hey, it seems to be conflicting with the main branch. would you look after this issue.
Thanks a lot for your contribution. 
Looking forward for more such resources which helps others and make the community grow. ❤

**Comment by swatiaggrawal** [comment]
i will surely do

**Comment by swatiaggrawal** [comment]
please check @debrajhyper

**Comment by debrajhyper** [comment]
Thanks a lot @swatiaggrawal for your contributions. 
Looking forward for more contributions. ❤

**Pull request merged**
