### PR TITLE
Fix #232 Added Kotlin resources

### LINKED ISSUE #232: Add Kotlin doc resources for Android
I will be adding ```Kotlin``` resources.

### PR DESCRIPTION
**Pull request by Chandra-Sekhar-Bala**
Fixes #232 
Added ```Kotlin``` resources which are from :
1. Official Android team
2. W3School

### CODE REVIEW

**Comment by Chandra-Sekhar-Bala** [comment]
Please check @debrajhyper.

**Comment by debrajhyper** [comment]
hey, @Chandra-Sekhar-Bala can you add the Kotlin Official in the Official Documentation section.

**Comment by Chandra-Sekhar-Bala** [comment]
Sure, I'll do it asap!

**Comment by Chandra-Sekhar-Bala** [comment]
Kotlin official doc was already added on ```Official Documentation```->```Programming language``` section. Well, I've removed redundant resource added by me. Please review @debrajhyper.

**Pull request merged**
